window.AUAUSAVE_DATA = {
  seed: {
    artists: [
      {
        id: "duo",
        name: "AUAUSAVE",
        realName: "อู่อู๋เซฟ",
        role: "COUPLE · #AuauSave",
        birth: "Our journey together",
        color: "linear-gradient(145deg,#f6b7aa,#d95d62 58%,#784c68)",
        initial: "AS",
        bio: "อู่อู๋ ธนภูมิ และ เซฟ วรพงษ์ คู่พาร์ตเนอร์นักแสดงจาก DOMUNDI ที่เป็นที่รู้จักจากซีรีส์ Your Sky และก้าวสู่บทนำร่วมกันใน Mr. Fanboy รักสุดใจนายแฟนบอย",
      },
      {
        id: "auau",
        name: "AUAU",
        realName: "ธนภูมิ เศรษฐสิทธิกุล",
        role: "ACTOR · SOLO ARTIST · DEXX",
        birth: "8 มีนาคม 2545",
        color: "linear-gradient(145deg,#b7d8d5,#3c7180)",
        initial: "A",
        bio: "อู่อู๋ ธนภูมิ นักแสดงและศิลปินค่าย DOMUNDI / DMD MUSIC สมาชิกวง DEXX และศิลปินเดี่ยวเจ้าของซิงเกิล “ไม่เล่น?”",
      },
      {
        id: "save",
        name: "SAVE",
        realName: "วรพงษ์ วาเลาะ",
        role: "ACTOR · ARTIST",
        birth: "27 มิถุนายน 2546",
        color: "linear-gradient(145deg,#f5daa0,#d58c61)",
        initial: "S",
        bio: "เซฟ วรพงษ์ นักแสดงค่าย DOMUNDI ผู้รับบทสำคัญใน Your Sky และก้าวสู่การเป็นนักแสดงนำใน Mr. Fanboy รักสุดใจนายแฟนบอย",
      },
    ],
    events: [],
    awards: [
      {
        id: "r1",
        artistId: "duo",
        year: "2026",
        title: "BL Supporting Duo – People’s Choice Award",
        org: "The Viral Hits Love Moment Awards 2026",
        source: "https://x.com/search?q=%23LoveMomentAwards2026xDMD",
      },
    ],
    videos: [
      {
        id: "v1",
        artistId: "duo",
        title: "Mr. Fanboy รักสุดใจนายแฟนบอย",
        views: "ผลงานซีรีส์คู่",
        url: "https://www.youtube.com/results?search_query=Mr+Fanboy+Auau+Save",
        embedUrl: "",
        category: "variety",
        featured: "yes",
        color: "linear-gradient(135deg,#e97368,#733f55)",
      },
      {
        id: "v2",
        artistId: "auau",
        title: "ไม่เล่น? — AUAU",
        views: "Solo Single · DMD MUSIC",
        url: "https://www.youtube.com/results?search_query=AUAU+ไม่เล่น+DMD+MUSIC",
        embedUrl: "",
        category: "auau",
        featured: "no",
        color: "linear-gradient(135deg,#638c94,#233c4a)",
      },
      {
        id: "v3",
        artistId: "duo",
        title: "ถิ่นพี่หนูชอบ EP.1 — AuAu & Save",
        views: "AuauSave in Hua Hin",
        url: "https://www.youtube.com/results?search_query=ถิ่นพี่หนูชอบ+Auau+Save",
        embedUrl: "",
        category: "variety",
        featured: "no",
        color: "linear-gradient(135deg,#e6be72,#a76445)",
      },
      {
        id: "v4",
        artistId: "auau",
        title: "Skinship — DEXX",
        views: "Official song · 2:56",
        url: "https://www.youtube.com/results?search_query=DEXX+Skinship+Official",
        embedUrl: "",
        category: "dexx",
        featured: "no",
        color: "linear-gradient(135deg,#526a91,#93b6c9)",
      },
      {
        id: "v5",
        artistId: "auau",
        title: "CLANG CLANG — DEXX",
        views: "Official song · 2:53",
        url: "https://www.youtube.com/results?search_query=DEXX+CLANG+CLANG+Official",
        embedUrl: "",
        category: "dexx",
        featured: "no",
        color: "linear-gradient(135deg,#6d4d87,#d886a8)",
      },
      {
        id: "v6",
        artistId: "auau",
        title: "รักได้แล้ว (NEXT STATUS) — DEXX",
        views: "Ost. ด้วงกับเธอ · 3:45",
        url: "https://www.youtube.com/results?search_query=DEXX+รักได้แล้ว+NEXT+STATUS+Official+MV",
        embedUrl: "",
        category: "dexx",
        featured: "no",
        color: "linear-gradient(135deg,#ef8b74,#f2c65f)",
      },
    ],
    presenters: [
      {
        id: "p1",
        artistId: "duo",
        brand: "Ri’che Biome",
        role: "Brand Presenter",
        year: "2025",
        color: "#8c6bb1",
        url: "",
      },
      {
        id: "p2",
        artistId: "duo",
        brand: "Clearasoft",
        role: "Brand Presenter",
        year: "2026",
        color: "#61a6b5",
        url: "",
      },
      {
        id: "p3",
        artistId: "auau",
        brand: "Dr.Choice",
        role: "Presenter",
        year: "2026",
        color: "#df785f",
        url: "",
      },
    ],
  },
  ARTIST_ID_ALIASES: {
    duo: 'AT01',
    auau: 'AT02',
    save: 'AT03',
    mp: 'AT04',
    a1783509325576: 'AT04',
    AT01: 'AT01',
    AT02: 'AT02',
    AT03: 'AT03',
    AT04: 'AT04',
  },
  DEFAULT_PAGE_CONTENT: {
    home: { th:{eyebrow:'บ้านแฟนคลับอู่อู๋เซฟ',title:'OUR HOUSE.\nOUR STORY.',description:'บ้านแฟนคลับของอู่อู๋เซฟ พื้นที่เก็บทุกโมเมนต์ของ #AuauSave'}, en:{eyebrow:'AUAUSAVE FANBASE',title:'OUR HOUSE.\nOUR STORY.',description:'The fan home for AuauSave, keeping every shared moment and every journey close.'} },
    artists: { th:{eyebrow:'AUAUSAVE HOUSE archive',title:'ศิลปินของเรา',description:'ทำความรู้จักอู่อู๋เซฟ ทั้งพาสคู่และพาสเดี่ยว'}, en:{eyebrow:'AUAUSAVE HOUSE ARCHIVE',title:'AUAUSAVE',description:'Meet Auau and Save through their couple and solo journeys.'} },
    schedule: { th:{eyebrow:'อดีต · ปัจจุบัน · อนาคต',title:'ปฏิทินงาน',description:'ย้อนดูงานที่ผ่านมา และวางแผนติดตามงานในอนาคต'}, en:{eyebrow:'PAST · PRESENT · FUTURE',title:'Event Calendar',description:'Review past events and plan for every upcoming schedule.'} },
    presenters: { th:{eyebrow:'แบรนด์และพาร์ตเนอร์',title:'พรีเซนเตอร์',description:'รวมแบรนด์ที่ร่วมเดินทางกับอู่อู๋เซฟ ทั้งงานคู่และงานเดี่ยว'}, en:{eyebrow:'BRAND & PARTNERSHIP',title:'Presenters',description:'Brands partnering with AuauSave across couple and solo projects.'} },
    awards: { th:{eyebrow:'AUAUSAVE HOUSE archive',title:'รางวัล',description:'ทุกความสำเร็จที่เราอยากร่วมฉลองไปด้วยกัน'}, en:{eyebrow:'AUAUSAVE HOUSE ARCHIVE',title:'Awards',description:'Every achievement we are proud to celebrate together.'} },
    videos: { th:{eyebrow:'ดู · ฟัง · จดจำ',title:'YouTube',description:'วิดีโอหลักและคลังรายการของ AUAUSAVE HOUSE'}, en:{eyebrow:'WATCH · LISTEN · REMEMBER',title:'YouTube',description:'Featured videos and the AUAUSAVE HOUSE video archive.'} }
  },
  DEFAULT_HOME_CARDS: {
    couplePath:{label:'การ์ดพาสคู่',eyebrow:'01 · COUPLE PATH',title:'AuauSave',description:'#AuauSave · Couple · Awards · Our moments',cta:'Explore couple path ↗'},
    soloPath:{label:'การ์ดพาสเดี่ยว',eyebrow:'02 · SOLO PATH',title:'Solo journeys',description:'Follow each artist’s solo events and awards separately',cta:''},
    scheduleDuo:{label:'การ์ดตารางงานคู่',eyebrow:'COUPLE PATH',title:'Couple Schedule',description:'#AuauSave',cta:''},
    scheduleAuau:{label:'การ์ดตารางงาน AUAU',eyebrow:'SOLO PATH',title:'Schedule AUAU',description:'Auau · DEXX',cta:''},
    scheduleSave:{label:'การ์ดตารางงาน SAVE',eyebrow:'SOLO PATH',title:'Schedule SAVE',description:'Save',cta:''}
  },
  DEFAULT_YOUTUBE_CATEGORIES: [
    {id:'auau', title:'AUAU', description:'Solo work and behind-the-scenes moments from Auau', linkLabel:'', linkUrl:''},
    {id:'dexx', title:'AUAU · DEXX', description:'Auau’s music and performances as a member of DEXX', linkLabel:'DEXX Official TH ↗', linkUrl:'https://www.youtube.com/@DEXXOfficialTH'},
    {id:'variety', title:'AUAUSAVE', description:'Series, variety shows and interviews', linkLabel:'', linkUrl:''},
  ],
};
